### ISSUE TITLE
HttpClient is actually required

### ISSUE THREAD

**Issue by worthy7** [Jericho/ZoomNet#103]
```
System.ArgumentNullException: Value cannot be null. (Parameter 'httpClient')
   at ZoomNet.Utilities.OAuthTokenHandler..ctor(OAuthConnectionInfo connectionInfo, HttpClient httpClient, Nullable`1 clockSkew)
   at ZoomNet.ZoomClient..ctor(IConnectionInfo connectionInfo, HttpClient httpClient, Boolean disposeClient, ZoomClientOptions options, ILogger logger)
   at ZoomNet.ZoomClient..ctor(IConnectionInfo connectionInfo, ZoomClientOptions options, ILogger logger)

```
I'm getting this error when trying to use:
`new ZoomClient(connectionInfo) ` as per the readme

Perhaps make `HttpClient `a required parameter if it is?

**Comment by Jericho** [comment]
Thanks for bringing this to my attention.

The `httpClient` is necessary for the OAuthTokenHandler and for other purposes as well but a default one is supposed to be transparently instantiated if the developer does not provide one. You found a scenario where, unfortunately, it's not working as intended.

As a temporary workaround you can use any of the other constructors of the `ZoomClient` class while I figure out and fix this issue. Something like this:
```csharp
var zoomClient = new ZoomClient(connectionInfo, (IWebProxy)null);
```
