### ISSUE TITLE
MeetingParticipantJoinedEvent deserialization issue

### ISSUE THREAD

**Issue by chiarapivetta** [Jericho/ZoomNet#228]
I'm using the Zoom Webhooks and it raises an exception when I try to deserialize the recived json to a MeetingParticipantJoinedEvent object. I found out, by looking in the Zoom documentation, that the MeetingId in the JSON schema is not always an Int64, but in some events it's a String!

![image](https://user-images.githubusercontent.com/38748810/178964090-df7de452-af8f-4b07-a511-9e01bc326f19.png)

![image](https://user-images.githubusercontent.com/38748810/178967084-26de4537-95c1-4fa7-9fed-b7c64d929ae9.png)

If the meeting id is a String it gives me this exception:
<details>
  <summary>Click to view stack trace</summary>
  
System.Text.Json.JsonException: The JSON value could not be converted to System.Int64. Path: $.id | LineNumber: 0 | BytePositionInLine: 270.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'String' as a number.
   at System.Text.Json.Utf8JsonReader.TryGetInt64(Int64& value)
   at System.Text.Json.Utf8JsonReader.GetInt64()
   at System.Text.Json.Serialization.Converters.Int64Converter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Converters.JsonMetadataServicesConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadUsingMetadata[TValue](JsonElement element, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](JsonElement element, JsonSerializerOptions options)
   at ZoomNet.Internal.ToObject[T](JsonElement element, JsonSerializerOptions options)
   at ZoomNet.Json.MeetingConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Converters.JsonMetadataServicesConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadUsingMetadata[TValue](JsonElement element, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](JsonElement element, JsonSerializerOptions options)
   at ZoomNet.Internal.ToObject[T](JsonElement element, JsonSerializerOptions options)
   at ZoomNet.Json.WebHookEventConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at ZoomNet.WebhookParser.ParseEventWebhook(String requestBody)
</details>

**Comment by Jericho** [comment]
I noticed this inconsistency in the documentation and [I asked for guidance on the Zoom forum](https://devforum.zoom.us/t/the-data-type-of-meetingid-is-inconsistent-in-webhook-documentation/70090). I haven't received any answer so far, unfortunately.

In the mean time, I am searching for a solution that would allow us to deserialize the meeting id no matter it's data type in the JSON string we receive from Zoom.

**Comment by Jericho** [comment]
Found a solution that turned out to be simpler than I expected: during my research I found out that there's a new setting that was added in .NET 5 which allows you to configure whether a given numerical property can only deserialized from a numerical value in the corresponding JSON node (this is called "strict" mode, and it's the default mode) or whether you also allow deserializing from string values.

Therefore, the solution is to simply enable the "allow reading from string" mode on the Meeting.Id property by decorating with the following attribute:
```charp
[JsonNumberHandling(JsonNumberHandling.AllowReadingFromString)]
```
