### ISSUE TITLE
Get Meeting Participants error

### ISSUE THREAD

**Issue by smblock** [Jericho/ZoomNet#237]
I looked through the other issues and didn't see one about this.  When I try to get the participants list of a live meeting it throws an error, based on the ParticipantDevice enum.  See log below.

Context:
When calling ZoomNet.Resource.IDashboards GetMeetingParticipantsAsync() in a web application it returns the following error: There is no value in the ParticipantDevice enum that corresponds to 'Web'.

My call looks like this: 
var zoomparticipantRecords = await client.Dashboards.GetMeetingParticipantsAsync(meetingId); 
where client is a ZoomNet.ZoomClient.

Stack Trace:
```
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.ArgumentException: There is no value in the ParticipantDevice enum that corresponds to 'Web'.
         at ZoomNet.Internal.ToEnum[T](String str)
         at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
         at ZoomNet.Json.ParticipantDeviceConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
         at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.Converters.JsonMetadataServicesConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
         at System.Text.Json.JsonSerializer.ReadUsingMetadata[TValue](JsonElement element, JsonTypeInfo jsonTypeInfo)
         at System.Text.Json.JsonSerializer.Deserialize[TValue](JsonElement element, JsonSerializerOptions options)
         at ZoomNet.Internal.AsPaginatedResponseWithToken[T](HttpContent httpContent, String propertyName, JsonSerializerOptions options, CancellationToken cancellationToken)
         at ZoomNet.Internal.AsPaginatedResponseWithToken[T](IRequest request, String propertyName, JsonSerializerOptions options)
         at WebApplication.Services.Zoom.GetParticipants(String meetingId) in C:\git\WebApplication\Library\Services\Zoom.cs:line 20
         at WebApplication.Areas.Api.Controllers.ZoomController.Participants(String meetingId) in C:\git\WebApplication\Areas\Api\Controllers\ZoomController.cs:line 30
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by Jericho** [comment]
This is surprising because "Web" is **NOT** documented as one of the valid value for a participant device. According to Zoom's own documentation, the possible values are:

> The type of device the participant used to join the meeting:
Phone — The participant joined via PSTN.
H.323/SIP — The participant joined via an H.323 or SIP device.
Windows — The participant joined via VoIP using a Windows device.
Mac — The participant joined via VoIP using a Mac device.
iOS — The participant joined via VoIP using an iOS device.
Android — The participant joined via VoIP using an Android device.
Note: This response returns an empty string (““) value for any users who are not a part of the host's account (external users).
Allowed: Phone┃H.323/SIP┃Windows┃Mac┃iOS┃Android

However, your situation clearly demonstrates that the documented list of possible values is not complete and "Web" should be added to this list.

**Comment by smblock** [comment]
@Jericho, thank you for making this change so quickly!
