### ISSUE TITLE
PropertyName for Status is incorrect in Registrant model

### ISSUE THREAD

**Issue by rossacartwright** [Jericho/ZoomNet#38]
PropertyName is currently "comments" but should be "status"

    /// <summary>
    /// Gets or sets the status.
    /// </summary>
    [JsonProperty(PropertyName = "comments")]
    public RegistrantStatus Status { get; set; }

As a result the following error is returned when `AddRegistrantAsync` is called:

    Message: A member with the name 'comments' already exists on 'ZoomNet.Models.Registrant'. 
    Use the JsonPropertyAttribute to specify another name.
    Source: Newtonsoft.Json
        at Newtonsoft.Json.Serialization.JsonPropertyCollection.AddProperty(JsonProperty property)
        at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties(Type type, 
        MemberSerialization memberSerialization)
        at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
        at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
        at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
        at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
        at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
        at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
        at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
        at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
        at ZoomNet.Utilities.Extensions.<AsObject>d__28`1.MoveNext()

**Comment by Jericho** [comment]
Thanks for pointing this out. It looks like a copy/paste mistake. I’ll look into it today.
